### ISSUE TITLE
structure for analytics app

### ISSUE THREAD

**Issue by drproduck** [drproduck/Element-Analytics#43]
how should analytics be accessed? (e.g for each file, list of files, no file required ...)

First stage: Parse
1. Offer pre-written parser. Or ..
2. let user choose regex, search patterns, extract lines ..
3. save extracted csv file for later use. (Also save to database? How to handle dynamic fields?)

Second stage: analysis
4. let user invoke saved csv file (how to organize extracted file and raw file?)
5.  Let user query (query what?)
6. Graph (what types of plot? what numerical values?)
7. Analysis (what statistics? what algorithms? what suggestions?)

Any other functions or options?

Professor's example use cases:

Use Case 1: Compute/VM - look for "DockerServerController".
e.g.you will see this entry in logs
2017-09-19 16:01:29.890  INFO 97625 --- [nio-9090-exec-6] c.d.w.s.provider.DockerServerController  : Find all managed docker-servers
Find example:
Find docker-server by id [40288184527bc4d401527bd7f9d10002]
Search example:
Search docker-server term [home] page [0] pageSize [10]

Use Case 2: Volumes - look for 'DockerVolumeController'
e.g. you will see this entry in logs
2017-09-19 16:04:37.616  INFO 97625 --- [nio-9090-exec-5] c.d.w.s.provider.DockerVolumeController  : Find all Volume.

Use Case 3: Containers - look for 'ProvisionController'
e.g. you will see this entry in logs
2017-09-19 16:06:07.581  INFO 97625 --- [nio-9090-exec-4] c.d.w.s.provision.ProvisionController    : Find all Provisions.

Use Case 4: Blueprints - look for 'BlueprintController'
e.g. you will see this in logs -
2017-09-19 16:07:04.898  INFO 97625 --- [nio-9090-exec-4] c.d.w.s.blueprint.BlueprintController    : Filter Blueprint by term [MY] page [0] pageSize [20]

**Comment by LyNgnH** [comment]
First stage:
- Pre-written parser is the safer choice.
- CSV files will be saved on local file system and processed entirely with pandas. Besides, there is not much of a benefit if saved in database.
 
Second stage:
- Raw file will be removed (to much space) after converted to csv, and we don't need raw files any more since we alreay extracted all important data in csv format.
-  We will break query feature into multiple options. For example:
   + Query by date: list, count all events that occurred between dates.
   + By type: list, count number of ERROR-type events.
   + By keyword: list, count number of events that contain certain keywords
   + Find a certain log entry given some criteria.
   + All the required use cases by Professor and potentially more...

Graph:
- General statistic graphs: some graphs at the dash board shoud present meta data about the user instead of going into detail of the log data. Something like user activity history (not sure), user storage usage (i.e. how much data user have left before they reach the storage limit).
-  Details: These are per logfile. Size of file over limit cap, how many log entries, frequency of events per date, percentage of ERROR | INFO | WARN events, percentage of each type of log (tomcat, nginx, solr, redis, etc.)

**Comment by drproduck** [comment]
I did not mean to exclude one of 2 options: whether to have a pre-written parser or to let user define on their own. There can be use case when user want to extract keywords, not the whole message for example. Or when they have a log file of different arrangement.
Second, there can be case when user wants to add more columns to the existing csv file. For example, the professor's log file's message column does not provide anything as is, they will want to extract certain things from it, and add them as new columns, or even create a new csv file.
Third, stemming from above, the log file might have information that is not usable at one time and users dont want to extract it yet, but that will be useful later. Thus we can keep the log and leave the decision to delete it to users. (In reality, we might even charge users for storage capacity, so it's up to users, not our need for optimization)

**Comment by LyNgnH** [comment]
To answer your second point, simple, we don't let them add more column to the csv. CSV files are read-only. I don't see what's so useful out of this.

Third point, I believe everything the parser extracts are all users need (even redundant).

Again, you are making this more complicated than it actually is. My answer above is a compromise between the problem and solution. You can pull anything out of your head and say "why don't we do this or that because in the future it could be this and that, blah blah blah?" Of course we can do what you suggested, but is it strictly necessary to provide the basic use cases of this project? Remember how much time we've got.

Feel free to do what you want, but show us the solution (i.e. code), not these long paragraphs because they don't do jack shit.

Stop making things up and start coding.
